import os
import csv
from datetime import datetime
from sqlalchemy.orm import Session
from app import models

def generate_excel_report(db: Session, project_id: int, report_type: str, generated_by_id: int) -> str:
    # 1. Fetch database records
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    project_name = project.project_name if project else f"Project #{project_id}"
    location = project.location if project else "Site Location"
    budget = project.budget if project else 0.0
    status = project.status if project else "Running"

    user = db.query(models.User).filter(models.User.id == generated_by_id).first()
    author_name = user.name if user else "Project Auditor"

    inventory_items = db.query(models.Inventory).filter(models.Inventory.project_id == project_id).all()
    resources = db.query(models.Resource).filter(models.Resource.project_id == project_id).all()
    procurements = db.query(models.Procurement).filter(models.Procurement.project_id == project_id).all()
    milestones = db.query(models.ProjectMilestone).filter(models.ProjectMilestone.project_id == project_id).all()
    workers = db.query(models.Worker).filter(models.Worker.project_id == project_id).all()

    # 2. Ensure output directory exists
    reports_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "static", "reports")
    os.makedirs(reports_dir, exist_ok=True)

    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{project_id}_{timestamp_str}.csv"
    file_path = os.path.join(reports_dir, filename)

    total_procurement_cost = sum(p.total_cost for p in procurements)
    total_payroll_estimate = sum(w.salary for w in workers)

    # 3. Write structured CSV Excel report
    with open(file_path, mode='w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)

        # Title & Meta Header
        writer.writerow(["BUILDTRACK CONSTRUCTION MANAGEMENT"])
        writer.writerow([f"REPORT TYPE: {report_type.upper()}"])
        writer.writerow([f"Project: {project_name}", f"Location: {location}", f"Status: {status}"])
        writer.writerow([f"Generated By: {author_name}", f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}"])
        writer.writerow([])

        # Financial & Executive Summary Section
        writer.writerow(["--- EXECUTIVE FINANCIAL OVERVIEW ---"])
        writer.writerow(["Metric Description", "Value"])
        writer.writerow(["Total Allocated Contract Budget ($)", f"${budget:,.2f}"])
        writer.writerow(["Material Procurement Expenditures ($)", f"${total_procurement_cost:,.2f}"])
        writer.writerow(["Estimated Workforce Payroll Cost ($)", f"${total_payroll_estimate:,.2f}"])
        writer.writerow(["Active Inventory Line Items", str(len(inventory_items))])
        writer.writerow(["Deployed Machinery Assets", str(len(resources))])
        writer.writerow(["Registered Workforce Members", str(len(workers))])
        writer.writerow(["Milestones Recorded", str(len(milestones))])
        writer.writerow([])

        # Resource Utilization Breakdown
        if "Resource" in report_type or "Progress" in report_type or "Daily" in report_type or True:
            if inventory_items:
                writer.writerow(["--- MATERIAL INVENTORY STOCK BREAKDOWN ---"])
                writer.writerow(["Material Name", "Category", "Current Stock", "Unit", "Min Stock", "Supplier"])
                for item in inventory_items:
                    writer.writerow([
                        getattr(item, "material_name", "Material"),
                        getattr(item, "category", "Cement"),
                        getattr(item, "quantity", 0),
                        getattr(item, "unit", "Units"),
                        getattr(item, "minimum_stock", 10),
                        getattr(item, "supplier", "Supplier")
                    ])
                writer.writerow([])

            if resources:
                writer.writerow(["--- HEAVY MACHINERY & EQUIPMENT ALLOCATION ---"])
                writer.writerow(["Equipment Name", "Category", "Quantity", "Operational Status"])
                for res in resources:
                    writer.writerow([
                        getattr(res, "name", getattr(res, "resource_name", "Equipment")),
                        getattr(res, "category", "Machinery"),
                        getattr(res, "quantity", 1),
                        getattr(res, "status", "Available")
                    ])
                writer.writerow([])

        # Workforce Roster Breakdown
        if "Workforce" in report_type or "Progress" in report_type:
            if workers:
                writer.writerow(["--- WORKFORCE ROSTER & PAYROLL SUMMARY ---"])
                writer.writerow(["Worker Name", "Designation", "Phone Contact", "Salary / Wage ($)"])
                for w in workers:
                    writer.writerow([
                        getattr(w, "name", "Worker"),
                        getattr(w, "designation", "Staff"),
                        getattr(w, "phone", "N/A") or "N/A",
                        f"${getattr(w, 'salary', 0):,.2f}"
                    ])
                writer.writerow([])

        # Procurement Ledger Breakdown
        if "Procurement" in report_type or "Progress" in report_type:
            if procurements:
                writer.writerow(["--- PROCUREMENT ORDERS & VENDOR FULFILLMENT LEDGER ---"])
                writer.writerow(["Material Item", "Supplier", "Quantity", "Total Cost ($)", "Payment Status"])
                for p in procurements:
                    writer.writerow([
                        getattr(p, "material_name", "Material"),
                        getattr(p, "supplier", "Vendor"),
                        getattr(p, "quantity", 0),
                        f"${getattr(p, 'total_cost', 0):,.2f}",
                        getattr(p, "payment_status", "Pending")
                    ])
                writer.writerow([])

        # Milestones Section
        if milestones:
            writer.writerow(["--- PROJECT CONSTRUCTION MILESTONES & PROGRESS SCHEDULE ---"])
            writer.writerow(["Milestone Phase", "Target Due Date", "Phase Status"])
            for ms in milestones:
                writer.writerow([
                    getattr(ms, "name", "Construction Phase"),
                    str(getattr(ms, "due_date", "On Schedule")),
                    getattr(ms, "status", "In Progress")
                ])
            writer.writerow([])

        writer.writerow(["BuildTrack Automated Construction Intelligence Report - Confidential"])

    return f"http://127.0.0.1:8000/static/reports/{filename}"
