import os
from datetime import datetime
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

from app import models

def generate_pdf_report(db: Session, project_id: int, report_type: str, generated_by_id: int) -> str:
    # 1. Fetch database records
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    project_name = project.project_name if project else f"Project #{project_id}"
    location = project.location if project else "Site Location"
    budget = project.budget if project else 0.0
    status = project.status if project else "Running"

    user = db.query(models.User).filter(models.User.id == generated_by_id).first()
    author_name = user.name if user else "Project Auditor"

    inventory_items = db.query(models.Inventory).filter(models.Inventory.project_id == project_id).all()
    resources = db.query(models.Resource).filter(models.Resource.project_id == project_id).all()
    procurements = db.query(models.Procurement).filter(models.Procurement.project_id == project_id).all()
    milestones = db.query(models.ProjectMilestone).filter(models.ProjectMilestone.project_id == project_id).all()

    # 2. Ensure output directory exists
    reports_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "static", "reports")
    os.makedirs(reports_dir, exist_ok=True)

    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{project_id}_{timestamp_str}.pdf"
    file_path = os.path.join(reports_dir, filename)

    # 3. Build PDF Document
    doc = SimpleDocTemplate(
        file_path,
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#1e293b')
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#ff7a00')
    )

    meta_style = ParagraphStyle(
        'MetaStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#64748b')
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#334155')
    )

    elements = []

    # Title Banner
    elements.append(Paragraph("BUILDTRACK CONSTRUCTION MANAGEMENT", subtitle_style))
    elements.append(Paragraph(report_type.upper(), title_style))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(f"Project: <b>{project_name}</b> | Location: {location} | Status: <b>{status}</b>", body_style))
    elements.append(Paragraph(f"Generated By: <b>{author_name}</b> | Date: <b>{datetime.now().strftime('%Y-%m-%d %H:%M')}</b>", meta_style))
    elements.append(Spacer(1, 10))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#ff7a00'), spaceAfter=15))

    # Executive Summary Section
    elements.append(Paragraph("Executive Summary", section_heading))
    summary_text = (
        f"This official analytical report outlines the operational status, financial budget allocation, inventory stocks, "
        f"and heavy equipment utilization for <b>{project_name}</b>. "
        f"The total project contract value is budgeted at <b>${budget:,.2f}</b> under current status <b>{status}</b>."
    )
    elements.append(Paragraph(summary_text, body_style))
    elements.append(Spacer(1, 12))

    # Key Performance Metrics Table
    elements.append(Paragraph("Project Financial Overview", section_heading))
    metrics_data = [
        ["Metric Description", "Amount / Status"],
        ["Total Allocated Contract Budget", f"${budget:,.2f}"],
        ["Material Procurement Expenditures", f"${sum(p.total_cost for p in procurements):,.2f}"],
        ["Active Inventory Line Items", str(len(inventory_items))],
        ["Deployed Machinery Assets", str(len(resources))],
        ["Milestones Recorded", str(len(milestones))]
    ]
    t_metrics = Table(metrics_data, colWidths=[300, 240])
    t_metrics.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#f8fafc'))
    ]))
    elements.append(t_metrics)
    elements.append(Spacer(1, 15))

    # Inventory Stock Breakdown Table
    if inventory_items:
        elements.append(Paragraph("Material Inventory Stock Breakdown", section_heading))
        inv_data = [["Material Name", "Category", "Current Stock", "Unit", "Supplier"]]
        for item in inventory_items:
            inv_data.append([
                item.material_name,
                item.category or "Cement",
                str(item.quantity),
                item.unit or "Units",
                item.supplier or "Supplier"
            ])
        t_inv = Table(inv_data, colWidths=[150, 100, 80, 70, 140])
        t_inv.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ff7a00')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')])
        ]))
        elements.append(t_inv)
        elements.append(Spacer(1, 15))

    # Machinery & Equipment Allocation
    if resources:
        elements.append(Paragraph("Heavy Machinery & Equipment Deployment", section_heading))
        res_data = [["Equipment Name", "Category", "Quantity", "Operational Status"]]
        for res in resources:
            res_data.append([
                res.resource_name,
                res.category or "Machinery",
                str(res.quantity),
                res.status or "Available"
            ])
        t_res = Table(res_data, colWidths=[180, 120, 80, 160])
        t_res.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#3b82f6')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 8.5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0'))
        ]))
        elements.append(t_res)
        elements.append(Spacer(1, 15))

    # Footer Disclaimer
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceBefore=10, spaceAfter=8))
    elements.append(Paragraph("BuildTrack Automated Construction Intelligence Report - Confidential", meta_style))

    # 4. Build PDF
    doc.build(elements)

    # 5. Return static HTTP URL path
    return f"http://127.0.0.1:8000/static/reports/{filename}"
